# Generated by Django 2.0.2 on 2018-03-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20180308_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='message',
            field=models.CharField(max_length=200, verbose_name='信息'),
        ),
    ]
